-- Datos iniciales Mozzafiato (opcional). Correr DESPUÉS de schema.sql

-- Colaboradores de ejemplo (cámbialos luego en la app)
insert into colaboradores (id,nombre,rol,area,pin) values ('u_admin','Gustavo','encargado',null,'1111') on conflict (id) do nothing;
insert into colaboradores (id,nombre,rol,area,pin) values ('u_barra','Encargado Barra','encargado','barra','2222') on conflict (id) do nothing;
insert into colaboradores (id,nombre,rol,area,pin) values ('u_c1','Colaborador 1','colaborador','barra','0001') on conflict (id) do nothing;
insert into colaboradores (id,nombre,rol,area,pin) values ('u_c2','Colaborador 2','colaborador','piso','0002') on conflict (id) do nothing;
insert into colaboradores (id,nombre,rol,area,pin) values ('u_c3','Colaborador 3','colaborador','cocina','0003') on conflict (id) do nothing;

-- Catálogo (bitácoras Barra, Piso, Cocina)
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_0','barra','Lavar y desinfectar','Refrigerador',3) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_1','barra','Lavar y desinfectar','Licuadora 1',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_2','barra','Lavar y desinfectar','Licuadora 2',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_3','barra','Lavar y desinfectar','Tetera de agua caliente',3) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_4','barra','Desempolvar y pulir cristalería, losa y cubiertos','Tazas para café (chicas, medianas y grandes)',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_5','barra','Desempolvar y pulir cristalería, losa y cubiertos','Popotes y cucharas',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_6','barra','Desempolvar y pulir cristalería, losa y cubiertos','Jarras para cremar leche',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_7','barra','Desempolvar y pulir cristalería, losa y cubiertos','Botellas',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_8','barra','Desempolvar y pulir cristalería, losa y cubiertos','Contenedores plásticos y de cristal',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_9','barra','Desempolvar y pulir cristalería, losa y cubiertos','Cubiertos',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_10','barra','Desempolvar y pulir cristalería, losa y cubiertos','Copas',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_11','barra','Limpiar y desinfectar','Barra, paredes de la base interior y exterior',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_12','barra','Limpiar y desinfectar','Alacena y sus puertas (interior y exterior)',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_13','barra','Limpiar y desinfectar','Mueble cajonero (interior y exterior)',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_14','barra','Limpiar y desinfectar','Caja registradora',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_15','barra','Equipo especial','Mantenimiento Cafetera San Remo',7) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_16','barra','Equipo especial','Mantenimiento cafetera Breville mediana',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_17','barra','Equipo especial','Limpiar debajo de la cafetera profesional',3) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_18','barra','Lavar, desempolvar y desinfectar','Anaqueles',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_19','barra','Lavar, desempolvar y desinfectar','Repisas',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_20','barra','Lavar, desempolvar y desinfectar','Paredes',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_21','barra','Lavar, desempolvar y desinfectar','Pisos',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_22','barra','Lavar, desempolvar y desinfectar','Techo',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_23','barra','Artículos de limpieza y accesorios','Bote de basura',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_24','barra','Artículos de limpieza y accesorios','Trapos',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_25','barra','Artículos de limpieza y accesorios','Bote del trapeador',3) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_26','barra','Artículos de limpieza y accesorios','Trapeador',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_27','barra','Artículos de limpieza y accesorios','Tapete del piso',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_28','barra','Artículos de limpieza y accesorios','Escurridor de trastes',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_29','barra','Artículos de limpieza y accesorios','Tarja completa',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_30','piso','Parte de afuera','Barrer',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_31','piso','Parte de afuera','Lavar el piso',3) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_32','piso','Parte de afuera','Sacudir puertas de madera plegable',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_33','piso','Parte de afuera','Aplicar abrillantador a las puertas de madera plegable',7) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_34','piso','Parte de afuera','Sacudir fachada',3) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_35','piso','Parte de afuera','Desempolvar techo y pilares',3) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_36','piso','Parte de adentro','Barrer',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_37','piso','Parte de adentro','Trapear',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_38','piso','Parte de adentro','Limpiar puertas de cristal',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_39','piso','Parte de adentro','Desempolvar paredes deck',3) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_40','piso','Parte de adentro','Desempolvar muros, techos y vigas',3) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_41','piso','Parte de adentro','Aplicar líquido especial a paredes deck, puertas y mesas',7) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_42','piso','Parte de adentro','Limpiar patas de las mesas',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_43','piso','Parte de adentro','Lijar paredes de pecera',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_44','piso','Parte de adentro','Limpiar filtros de pecera',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_45','piso','Parte de adentro','Cambiar agua de la pecera',7) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_46','piso','Parte de adentro','Limpiar focos y lámparas de tronco de madera',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_47','piso','Parte de adentro','Limpiar lámpara de rueda de carreta',3) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_48','piso','Parte de adentro','Limpiar filtros y condensador de aire acondicionado',7) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_49','piso','Parte de adentro','Limpiar repisas de vasos',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_50','piso','Parte de adentro','Limpiar libros y sus repisas',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_51','piso','Parte de adentro','Limpiar sillas',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_52','piso','Parte de adentro','Limpiar vitrina',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_53','piso','Parte de adentro','Limpiar tapete sanitizante',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_54','piso','Parte de adentro','Lavar trapo de sanitizante',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_55','piso','Parte de adentro','Lavar trapos para limpiar mesas',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_56','piso','Parte de adentro','Pulir cubiertos',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_57','piso','Parte de adentro','Pulir vasos de la repisa',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_58','cocina','Lavar y desinfectar · Equipo frío','Congelador blanco',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_59','cocina','Lavar y desinfectar · Equipo frío','Refrigerador 1',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_60','cocina','Lavar y desinfectar · Equipo frío','Refrigerador 2',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_61','cocina','Lavar y desinfectar · Equipo frío','Refrigerador 3',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_62','cocina','Lavar y desinfectar · Equipo frío','Refrigerador 4',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_63','cocina','Lavar y desinfectar · Equipo caliente','Estufa',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_64','cocina','Lavar y desinfectar · Equipo caliente','Plancha',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_65','cocina','Equipo eléctrico caliente','Crepera',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_66','cocina','Equipo eléctrico caliente','Wafflera',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_67','cocina','Equipo eléctrico caliente','Paninera',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_68','cocina','Equipo eléctrico caliente','Horno de microondas',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_69','cocina','Equipo eléctrico frío','Batidora',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_70','cocina','Equipo eléctrico frío','Licuadora',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_71','cocina','Equipo eléctrico frío','Ventilador de pared',3) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_72','cocina','Lavar, desengrasar y desinfectar','Anaqueles',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_73','cocina','Lavar, desengrasar y desinfectar','Repisas',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_74','cocina','Lavar, desengrasar y desinfectar','Paredes',2) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_75','cocina','Lavar, desengrasar y desinfectar','Pisos',1) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_76','cocina','Lavar, desengrasar y desinfectar','Techo',3) on conflict (id) do nothing;
insert into catalogo (id,area,seccion,nombre,fr) values ('cat_77','cocina','Lavar, desengrasar y desinfectar','Campana',2) on conflict (id) do nothing;
